[project]
name = "senior-thesis"
version = "0.1.0"
description = "卒論関連"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "nltk>=3.9.2",
    "pandas>=2.3.3",
    "path>=17.1.1",
    "sentence-transformers>=5.1.2",
]
